### ISSUE TITLE
Can you show me the way to do POST/PUT ?

### ISSUE THREAD

**Issue by distravantari** [mikespook/wc-api-golang#2]
<img width="566" alt="screen shot 2017-05-22 at 10 35 09 am" src="https://cloud.githubusercontent.com/assets/10736018/26291713/7f142112-3eda-11e7-98ad-60510f0f6852.png">

can you help me with this? it post the product with a default value, it seems I still don't understand how to make a data interface.

thank you.

**Comment by mikespook** [comment]
You needn't do anything to `prod`, input it directly into the `Post` e.g.
`client.Post("products", prod)`

While it's early stage of the library, could have some issues internally. Feel free to open an issue.

**Comment by distravantari** [comment]
oh I thought I do that in the first place, Thank you so much.

**Comment by distravantari** [comment]
but why I can't post an image with this?
<img width="285" alt="screen shot 2017-05-26 at 11 23 32 am" src="https://cloud.githubusercontent.com/assets/10736018/26480670/c7be9d2e-4205-11e7-8622-773a1e3863d7.png">
